version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      labels: # Global options
        caddy.email: ajm.dosreis.daponte@gmail.com
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M
          
  whoami:
     image: containous/whoami
     networks:
       - caddy
     deploy:
       replica: 2
       labels:
         caddy: test.reges.fr
         caddy.reverse_proxy: "{{upstreams 80}}"
