version: "3.9"

networks:
  caddy:
    external: true

services:
  whoami:
    image: containous/whoami
    networks:
      - caddy
    deploy:
      replicas: 2
      labels:
        caddy: test.whoami.fr
        caddy.reverse_proxy: "{{ upstreams 80 }}"
